export default [
  {
    id: 1,
    avartar: 'https://example.com/avatar1.jpg',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    phone1: '123-456-7890',
    phone2: '987-654-3210',
    address: '123 Main St, Cityville, State, 12345',
    jobTitle: 'Software Engineer',
    department: 'IT',
    workDescription: 'Responsible for developing and maintaining software applications.',
    managerName: 'Jane Manager',
    startDate: '2022-01-01',
    skillName: 'Programming',
    skillDescription: 'Proficient in Java, JavaScript, and Python.',
    educationName: "Bachelor's in Computer Science",
    duration: '4 years',
    educationsDescription: 'Studied computer science at University XYZ.'
  },
  {
    id: 2,
    avartar: 'https://example.com/avatar2.jpg',
    firstName: 'Alice',
    lastName: 'Smith',
    email: 'alice.smith@example.com',
    phone1: '456-789-0123',
    phone2: '789-012-3456',
    address: '456 Oak St, Townsville, State, 54321',
    jobTitle: 'HR Specialist',
    department: 'HR',
    workDescription: 'Handles human resources tasks including recruitment and employee relations.',
    managerName: 'Bob HRManager',
    startDate: '2022-02-15',
    skillName: 'Recruitment',
    skillDescription: 'Experienced in talent acquisition and interviewing.',
    educationName: "Master's in Human Resources",
    duration: '2 years',
    educationsDescription: "Completed a master's degree in HR at University ABC."
  },
  {
    id: 3,
    avartar: 'https://example.com/avatar3.jpg',
    firstName: 'Mark',
    lastName: 'Johnson',
    email: 'mark.johnson@example.com',
    phone1: '789-012-3456',
    phone2: '012-345-6789',
    address: '789 Pine St, Villagetown, State, 67890',
    jobTitle: 'Marketing Specialist',
    department: 'Marketing',
    workDescription: 'Develops and executes marketing campaigns to promote company products.',
    managerName: 'Sara MarketingManager',
    startDate: '2022-03-20',
    skillName: 'Digital Marketing',
    skillDescription: 'Skilled in online marketing strategies.',
    educationName: "Bachelor's in Marketing",
    duration: '4 years',
    educationsDescription: "Earned a bachelor's degree in marketing at University DEF."
  },
  {
    id: 4,
    avartar: 'https://example.com/avatar4.jpg',
    firstName: 'Emily',
    lastName: 'Williams',
    email: 'emily.williams@example.com',
    phone1: '345-678-9012',
    phone2: '678-901-2345',
    address: '345 Cedar St, Hamletville, State, 23456',
    jobTitle: 'Financial Analyst',
    department: 'Finance',
    workDescription: 'Analyzes financial data and provides insights to support decision-making.',
    managerName: 'David CFO',
    startDate: '2022-04-10',
    skillName: 'Financial Analysis',
    skillDescription: 'Experienced in financial modeling and forecasting.',
    educationName: "Bachelor's in Finance",
    duration: '4 years',
    educationsDescription: "Completed a bachelor's degree in finance at University GHI."
  },
  {
    id: 5,
    avartar: 'https://example.com/avatar5.jpg',
    firstName: 'Chris',
    lastName: 'Brown',
    email: 'chris.brown@example.com',
    phone1: '567-890-1234',
    phone2: '890-123-4567',
    address: '567 Maple St, Boroughburg, State, 34567',
    jobTitle: 'Sales Representative',
    department: 'Sales',
    workDescription: 'Manages sales activities and builds relationships with clients.',
    managerName: 'Alex SalesManager',
    startDate: '2022-05-25',
    skillName: 'Sales Strategy',
    skillDescription: 'Skilled in developing and implementing effective sales strategies.',
    educationName: "Bachelor's in Business Administration",
    duration: '4 years',
    educationsDescription:
      "Earned a bachelor's degree in business administration at University JKL."
  },
  {
    id: 6,
    avartar: 'https://example.com/avatar6.jpg',
    firstName: 'Olivia',
    lastName: 'Davis',
    email: 'olivia.davis@example.com',
    phone1: '678-901-2345',
    phone2: '901-234-5678',
    address: '678 Elm St, Citytown, State, 45678',
    jobTitle: 'Customer Support Specialist',
    department: 'Customer Support',
    workDescription: 'Assists customers with product inquiries and resolves issues.',
    managerName: 'Tom SupportManager',
    startDate: '2022-06-30',
    skillName: 'Customer Service',
    skillDescription: 'Dedicated to providing excellent customer service.',
    educationName: "Associate's in Communication",
    duration: '2 years',
    educationsDescription: "Completed an associate's degree in communication at University MNO."
  },
  {
    id: 7,
    avartar: 'https://example.com/avatar7.jpg',
    firstName: 'Daniel',
    lastName: 'Martinez',
    email: 'daniel.martinez@example.com',
    phone1: '789-012-3456',
    phone2: '012-345-6789',
    address: '789 Oak St, Villagetown, State, 56789',
    jobTitle: 'IT Specialist',
    department: 'IT',
    workDescription: 'Provides technical support and maintains IT infrastructure.',
    managerName: 'Karen ITManager',
    startDate: '2022-07-15',
    skillName: 'IT Support',
    skillDescription: 'Skilled in troubleshooting and resolving IT issues.',
    educationName: "Bachelor's in Computer Science",
    duration: '4 years',
    educationsDescription: "Earned a bachelor's degree in computer science at University PQR."
  },
  {
    id: 8,
    avartar: 'https://example.com/avatar8.jpg',
    firstName: 'Sophia',
    lastName: 'Taylor',
    email: 'sophia.taylor@example.com',
    phone1: '890-123-4567',
    phone2: '123-456-7890',
    address: '890 Cedar St, Hamletville, State, 67890',
    jobTitle: 'Marketing Coordinator',
    department: 'Marketing',
    workDescription: 'Assists in planning and executing marketing initiatives.',
    managerName: 'Sara MarketingManager',
    startDate: '2022-08-20',
    skillName: 'Marketing Coordination',
    skillDescription: 'Coordinates marketing activities to promote brand awareness.',
    educationName: "Bachelor's in Marketing",
    duration: '4 years',
    educationsDescription: "Completed a bachelor's degree in marketing at University STU."
  },
  {
    id: 9,
    avartar: 'https://example.com/avatar9.jpg',
    firstName: 'Liam',
    lastName: 'Johnson',
    email: 'liam.johnson@example.com',
    phone1: '901-234-5678',
    phone2: '234-567-8901',
    address: '901 Maple St, Boroughburg, State, 78901',
    jobTitle: 'Financial Planner',
    department: 'Finance',
    workDescription: 'Provides financial planning services and investment advice.',
    managerName: 'David CFO',
    startDate: '2022-09-10',
    skillName: 'Financial Planning',
    skillDescription: 'Experienced in creating financial plans and managing investments.',
    educationName: "Master's in Finance",
    duration: '2 years',
    educationsDescription: "Completed a master's degree in finance at University VWX."
  },
  {
    id: 10,
    avartar: 'https://example.com/avatar10.jpg',
    firstName: 'Emma',
    lastName: 'Anderson',
    email: 'emma.anderson@example.com',
    phone1: '012-345-6789',
    phone2: '345-678-9012',
    address: '012 Elm St, Citytown, State, 89012',
    jobTitle: 'HR Generalist',
    department: 'HR',
    workDescription: 'Handles various HR tasks, including recruitment and employee relations.',
    managerName: 'Bob HRManager',
    startDate: '2022-10-05',
    skillName: 'Human Resources',
    skillDescription: 'Knowledgeable in various HR functions.',
    educationName: "Bachelor's in Human Resources",
    duration: '4 years',
    educationsDescription: "Earned a bachelor's degree in HR at University YZ."
  }
];
